apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: testgo-0618 
  janus-idp.io/tekton: testgo-0618
  backstage.io/kubernetes-id: testgo-0618
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: testgo-0618
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  