name: Trigger Target PipelineRun

on:
  workflow_dispatch:
    inputs:
      source_repo_url:
        description: 'Input the source repo URL that need to trigger the pipelinerun'
        required: true

jobs:
  trigger:
    runs-on: ubuntu-latest

    steps:
      - name: Check out source repo URL
        uses: actions/checkout@v4
        with:
          repository: stephanie-cy/testgo-0618
      - name: Trigger pipelinerun in source repo URL
        run: |
          sourceRepoURL="${{ github.event.inputs.source_repo_url }}"
          REPONAME=$(basename $sourceRepoURL)
          # echo "token is ${{ secrets.GITHUB_TOKEN }}"
          git config --global user.email "scaffolder@backstage.io"
          git config --global user.name "Scaffolder"
          git checkout -b trigger-build
          git commit --allow-empty -m "Trigger Build"
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          commit-message: 'ci: tigger pipeline build'
          delete-branch: true
          title: 'ci: tigger pipeline build'
          labels: |
              automated pr
              automerge